#define TOTAL_ERROR_TYPE 6

void InitDXErrorMsg(); //Initialise tout les messages pour les fichiers log
void ReportDxError(int result, int msgType, int msgId);

enum ERROR_TYPE
{
	WIN32_,
	DIRECT3D,
	DIRECTDRAW,
	DIRECTINPUT,
	DIRECTMUSIC,
	GDI
};

enum ERROR_WIN32
{
	ERR_REGISTERCLASS,
	ERR_CREATEWIN,
	ERR_SETTIMER
};

enum ERROR_DIRECT3D
{
	ERR_D3D_CREATEDEVICE,
	ERR_D3D_CREATETEXTURE,
	ERR_D3D_CREATEVERTEXBUFFER,
	ERR_D3D_SETRENDERSTATE,
	ERR_D3D_SETTRANSFORM,
	ERR_D3D_SETLIGHT,
	ERR_D3D_LIGHTENABLE,
	ERR_D3D_SETTEXTURE,
	ERR_D3D_SETTEXTURESTAGESTATE,
	ERR_D3D_SETSTREAMSOURCE,
	ERR_D3D_SETFVF,
	ERR_D3D_LOCK,
	ERR_D3D_UNLOCK,
	ERR_D3D_CLEAR,
	ERR_D3D_BEGINSCENE,
	ERR_D3D_DRAWPRIMITIVE,
	ERR_D3D_ENDSCENE,
	ERR_D3D_PRESENT
};

enum ERROR_DIRECTDRAW
{
	ERR_DD_DIRECTDRAWCREATE,
	ERR_DD_SETCOOPERATIVELEVEL,
	ERR_DD_SETDISPLAYMODE,
	ERR_DD_ENUMDISPLAYMODES,
	ERR_DD_SETHWND,
	ERR_DD_SETCLIPPER,
	ERR_DD_CREATESURFACE,
	ERR_DD_DESTROYSURFACE,
	ERR_DD_CREATECLIPPER,
	ERR_DD_GETATTACHEDSURFACE,
	ERR_DD_BLT,
	ERR_DD_SURFACELOST,
	ERR_DD_GETDEVICECONTEXT,
	ERR_DD_DELDEVICECONTEXT,
	ERR_DD_GETROTATEDBITMAP
};

enum ERROR_DIRECTINPUT
{
	ERR_DI_DIRECTINPUTCREATE,
	ERR_DI_CREATEDEVICE,
	ERR_DI_SETDATAFORMAT,
	ERR_DI_SETCOOPERATIVELEVEL,
	ERR_DI_GETDEVICESTATE
};

enum ERROR_DIRECTMUSIC
{
	ERR_DM_ANY
};

enum ERROR_GDI
{
	ERR_GDI_GETDC
};
